### ISSUE TITLE
Online Server (https://uncurl.cs.washington.edu/db_query) is Down 

### ISSUE THREAD

**Issue by dr-aheydari** [shunfumao/cellmesh#2]
Hi folks!

Thank you for the great tools; the API and the online interface have been very helpful for our research.

However, as of yesterday, the online server seems to be down, since the page shows the following error message:

> Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request [GET /db_query](https://uncurl.cs.washington.edu/db_query).
> 
> Reason: Error reading from remote server

I would really appreciate it if you could take a look into it and potentially resolve the issue.

Thank you very much in advance.

<img width="487" alt="Screen Shot 2022-04-20 at 8 26 54 PM" src="https://user-images.githubusercontent.com/36649087/164366048-04fefb76-569d-4192-bc10-9f9e35bddad4.png">
!

**Comment by yjzhang** [comment]
I'm very sorry that you're encountering this issue. The server is currently down due to docker deployment issues on the host's end; we are trying to fix it. In the meantime, it should be possible to use the docker image at https://hub.docker.com/repository/docker/ayuezhang27/uncurl-app.

**Comment by dr-aheydari** [comment]
Hi @yjzhang,

Thank you very much for sharing the container with me! I pulled the docker image and everything works great on my local machine!

Thank you very much for your quick and helpful response!
